import 'manifest.dart';

/// The TypedArray a column of each storage kind arrives as, and the TypeScript
/// type of one element.
const Map<String, (String, String)> _types = {
  'float32': ('Float32Array', 'number'),
  'float64': ('Float64Array', 'number'),
  'int32': ('Int32Array', 'number'),
  'uint32': ('Uint32Array', 'number'),
  'int64': ('BigInt64Array', 'bigint'),
  'uint8': ('Uint8Array', 'number'),
};

/// Writes the TypeScript a script author sees.
///
/// The typings are the whole developer experience for scripting: they are what
/// makes an editor useful for an engine the script never compiles against. So
/// they carry the guidance too — the doc comments say which calls are the slow
/// path and why, because a type that permits something is read as an
/// invitation.
class TypeScriptEmitter {
  const TypeScriptEmitter();

  String emit(List<ManifestComponent> components) {
    final buffer = StringBuffer();
    _writeHeader(buffer);
    _writeEntity(buffer);

    for (final component in components) {
      _writeComponent(buffer, component);
    }

    _writeRegistry(buffer, components);
    _writeQuery(buffer);
    _writeWorld(buffer);
    return buffer.toString();
  }

  void _writeHeader(StringBuffer buffer) {
    buffer
      ..writeln('// GENERATED by orbis_script_codegen. Do not edit.')
      ..writeln('//')
      ..writeln('// Describes the engine as this workspace\'s components')
      ..writeln('// define it. Read from the manifests each package publishes,')
      ..writeln('// so nothing here was compiled against the engine.')
      ..writeln();
  }

  void _writeEntity(StringBuffer buffer) {
    buffer
      ..writeln('/**')
      ..writeln(' * An entity handle: an index and a reuse counter packed')
      ..writeln(' * together.')
      ..writeln(' *')
      ..writeln(' * Branded, so an ordinary number cannot be passed where one')
      ..writeln(' * is expected. An invented handle is the mistake this catches')
      ..writeln(' * at compile time; a stale one is caught at run time, because')
      ..writeln(' * the counter no longer matches the slot.')
      ..writeln(' */')
      ..writeln('export type Entity = bigint & {')
      ..writeln('  readonly __orbisEntity: unique symbol;')
      ..writeln('};')
      ..writeln();
  }

  void _writeComponent(StringBuffer buffer, ManifestComponent component) {
    final (_, elementType) = _types[component.kind]!;

    buffer
      ..writeln('/**')
      ..writeln(' * ${component.name} — ${component.kind} '
          'x${component.arity}, from ${component.package}.')
      ..writeln(' *');
    if (component.replicated) {
      buffer.writeln(component.ownerWritable
          ? ' * Replicated, and writable by the client that owns the entity.'
          : ' * Replicated. The authority writes it; a client\'s attempt is'
              ' refused.');
    } else {
      buffer.writeln(' * Local to whichever machine it is on.');
    }
    buffer
      ..writeln(' */')
      ..writeln('export interface ${component.name} {');
    for (final field in component.fields) {
      buffer.writeln('  $field: $elementType;');
    }
    buffer
      ..writeln('}')
      ..writeln();
  }

  void _writeRegistry(
      StringBuffer buffer, List<ManifestComponent> components) {
    buffer
      ..writeln('/** Every component this workspace declares. */')
      ..writeln('export interface Components {');
    for (final component in components) {
      buffer.writeln('  ${component.name}: ${component.name};');
    }
    buffer
      ..writeln('}')
      ..writeln()
      ..writeln('export type ComponentName = keyof Components;')
      ..writeln()
      ..writeln('/** The array a component\'s column arrives as. */')
      ..writeln('export interface ComponentColumns {');
    for (final component in components) {
      buffer.writeln('  ${component.name}: ${_types[component.kind]!.$1};');
    }
    buffer
      ..writeln('}')
      ..writeln()
      ..writeln('/**')
      ..writeln(' * How many elements one entity occupies in a column.')
      ..writeln(' *')
      ..writeln(' * Entity `i` of a column starts at `i * arity`. A system')
      ..writeln(' * indexes with this rather than a literal, so a component')
      ..writeln(' * that gains a field does not silently misread.')
      ..writeln(' */')
      ..writeln('export declare const componentArity: {');
    for (final component in components) {
      buffer.writeln('  readonly ${component.name}: ${component.arity};');
    }
    buffer
      ..writeln('};')
      ..writeln();

    final replicated =
        components.where((c) => c.replicated).map((c) => c.name).toList();
    buffer
      ..writeln('/** Components that cross the wire. */')
      ..writeln('export declare const replicatedComponents: '
          'readonly ${_union(replicated)}[];')
      ..writeln();

    final writable = components
        .where((c) => c.replicated && c.ownerWritable)
        .map((c) => c.name)
        .toList();
    buffer
      ..writeln('/** Components the client owning an entity may write. */')
      ..writeln('export declare const ownerWritableComponents: '
          'readonly ${_union(writable)}[];')
      ..writeln();
  }

  /// A union, parenthesised so it can be made into an array.
  ///
  /// Without the brackets `readonly 'A' | 'B'[]` parses as a union of `'A'`
  /// and an array of `'B'`, which is a different type and a valid one — so
  /// only a type checker catches it.
  String _union(List<String> names) {
    if (names.isEmpty) return 'never';
    final quoted = names.map((name) => "'$name'").join(' | ');
    return names.length == 1 ? quoted : '($quoted)';
  }

  void _writeQuery(StringBuffer buffer) {
    buffer
      ..writeln('/**')
      ..writeln(' * One run of entities that all carry the queried')
      ..writeln(' * components.')
      ..writeln(' *')
      ..writeln(' * The columns are views onto the engine\'s own memory:')
      ..writeln(' * reading and writing them copies nothing and crosses')
      ..writeln(' * nothing. A run is valid until the next structural change —')
      ..writeln(' * creating or destroying an entity, or adding or removing a')
      ..writeln(' * component. Finish the loop, then mutate.')
      ..writeln(' */')
      ..writeln('export interface Chunk<Names extends readonly ComponentName[]> {')
      ..writeln('  readonly length: number;')
      ..writeln()
      ..writeln('  /** Handles, in the same order as every column. */')
      ..writeln('  readonly entities: BigUint64Array;')
      ..writeln()
      ..writeln('  column<K extends Names[number]>(name: K): ComponentColumns[K];')
      ..writeln('}')
      ..writeln()
      ..writeln('/**')
      ..writeln(' * A standing question about which entities carry a set of')
      ..writeln(' * components. Worth keeping across frames: the matching runs')
      ..writeln(' * are cached and only recomputed when the world\'s structure')
      ..writeln(' * changes.')
      ..writeln(' */')
      ..writeln('export interface Query<Names extends readonly ComponentName[]> {')
      ..writeln('  readonly chunks: ReadonlyArray<Chunk<Names>>;')
      ..writeln('  destroy(): void;')
      ..writeln('}')
      ..writeln();
  }

  void _writeWorld(StringBuffer buffer) {
    buffer
      ..writeln('/**')
      ..writeln(' * The engine, from a script.')
      ..writeln(' *')
      ..writeln(' * `get` and `add` cross into the engine once per call, which')
      ..writeln(' * is the right cost for spawning something or answering a')
      ..writeln(' * question about one entity. A system touching many entities')
      ..writeln(' * should take a `query` and work over its columns instead:')
      ..writeln(' * that crosses once per tick however many entities there are,')
      ..writeln(' * and it is the difference between a system that scales and')
      ..writeln(' * one that does not.')
      ..writeln(' */')
      ..writeln('export declare const world: {')
      ..writeln('  create(): Entity;')
      ..writeln('  destroy(entity: Entity): void;')
      ..writeln('  alive(entity: Entity): boolean;')
      ..writeln('  count(): number;')
      ..writeln()
      ..writeln('  has<K extends ComponentName>(entity: Entity, name: K): boolean;')
      ..writeln()
      ..writeln('  add<K extends ComponentName>(')
      ..writeln('    entity: Entity,')
      ..writeln('    name: K,')
      ..writeln('    value?: Partial<Components[K]>,')
      ..writeln('  ): void;')
      ..writeln()
      ..writeln('  remove<K extends ComponentName>(entity: Entity, name: K): boolean;')
      ..writeln()
      ..writeln('  /** Null when the entity does not carry it. */')
      ..writeln('  get<K extends ComponentName>(')
      ..writeln('    entity: Entity,')
      ..writeln('    name: K,')
      ..writeln('  ): Components[K] | null;')
      ..writeln()
      ..writeln('  query<const Names extends readonly ComponentName[]>(')
      ..writeln('    ...names: Names')
      ..writeln('  ): Query<Names>;')
      ..writeln('};')
      ..writeln();
  }
}
