import 'dart:convert';
import 'dart:io';

/// Puts the compiled scene runtime inside the Dart package that ships it.
///
/// The TypeScript in `js/` is the source; what a game's script actually loads
/// is the JavaScript it compiles to. Embedding that as a string rather than as
/// an asset means the package works wherever Dart does — a test, a console
/// front end, a build with no asset bundle — and means *using* it needs no
/// node toolchain at all. Only changing it does.
void main() {
  final built = Directory('build/js');
  final scene = File('${built.path}/scene.js');

  if (!scene.existsSync()) {
    stderr.writeln(
      'Nothing compiled in build/js. Run `npm run build:ui` from the '
      'repository root first — that is what compiles the TypeScript this '
      'embeds.',
    );
    exit(1);
  }

  final wrapped = _wrap({'scene': scene});

  File('lib/src/runtime.g.dart').writeAsStringSync('''
// Generated by tool/embed_runtime.dart from js/scene.ts. Do not edit.
//
// Checked in on purpose: this is what ships, not a build artefact. A game
// using this package should not need a TypeScript compiler in order to run,
// only in order to write.
//
// To change it: `npm run build:ui` at the repository root.

/// The scene runtime, as the script engine takes it.
///
/// Load this into a script host before any interface script. It defines the
/// elements, both JSX factories, and the `__orbis_ui` object the host renders
/// and dispatches through — and a small module registry, so that a file
/// compiled straight from TypeScript runs without being bundled first.
class SceneRuntime {
  const SceneRuntime._();

  /// How much JavaScript this is, so a host can budget for it.
  static const int length = ${wrapped.length};

  /// What the library answers `require` for. Anything else has to be bundled
  /// into the script before it is run.
  static const List<String> modules = ['orbis/scene'];

  static const String source = ${_dartString(wrapped)};
}
''');

  stdout.writeln('Embedded ${wrapped.length} characters of JavaScript.');
}

/// Wraps the compiled files so the engine can evaluate them as one script.
///
/// TypeScript emits `require` calls and the engine has no idea what a module
/// is. A bundler is the real answer for anything large — that is what every
/// engine of this shape does — but a single file asking for the library it was
/// written against should not need one, so the library registers itself and
/// answers by the last part of whatever path it is asked for.
String _wrap(Map<String, File> modules) {
  final defined = modules.entries
      .map(
        (entry) => 'define(${jsonEncode(entry.key)}, '
            'function (module, exports, require) {\n'
            '${entry.value.readAsStringSync()}\n});',
      )
      .join('\n');

  return '''
(function () {
  var modules = {};

  function define(name, factory) {
    var module = { exports: {} };
    factory(module, module.exports, ask);
    modules[name] = module.exports;
  }

  // By the last part of the path, so that "orbis/jsx-runtime",
  // "./jsx-runtime" and "../../js/jsx-runtime" all mean the one thing they
  // can mean here.
  function ask(id) {
    var name = String(id).split('/').pop().replace(/\\.js\$/, '');
    var shared = globalThis.__orbis_modules || {};
    if (Object.prototype.hasOwnProperty.call(modules, name)) {
      return modules[name];
    }
    if (Object.prototype.hasOwnProperty.call(shared, name)) {
      return shared[name];
    }
    throw new Error(
      "Orbis has nothing called '" + id + "'. It knows " +
        Object.keys(modules).join(', ') +
        ". Anything else has to be bundled into the script before it runs."
    );
  }

  if (typeof globalThis.require !== 'function') globalThis.require = ask;

$defined

  // So a host can register a game's own file under a name and then reach
  // what it exported, and so that two runtimes loaded together share one
  // registry rather than replacing each other's.
  globalThis.__orbis_modules =
      Object.assign(globalThis.__orbis_modules || {}, modules);
})();''';
}

/// The string as Dart source.
///
/// Quoted rather than raw, because the JavaScript contains both kinds of
/// quote. JSON encoding handles those and the backslashes, but not the dollar
/// signs — and the JavaScript is full of them, in its own template literals.
/// Dart would read every one as an interpolation, which is a compile error at
/// best and somebody else's variable at worst.
String _dartString(String value) =>
    jsonEncode(value).replaceAll(r'$', r'\$');
